### ISSUE TITLE
CAN Call function

### ISSUE THREAD

**Issue by rahularepaka** [arduino-libraries/Arduino_PortentaBreakout#48]
I am writing to communicate over CAN, but unable to do it since the function to call it is missing. Help!

**Comment by per1234** [comment]
Hi @rahularepaka. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/hardware/portenta/portenta-breakout/174
